"""Campaign schema — locked shape for PLAN.md Phase 10.

This file defines the persistent state model for multi-mission campaigns.
The shape is locked — adding fields later means writing migrations.

Three concepts:

  CampaignSpec  — the campaign definition (missions + branching rules).
                  Authored once; usually generated by the campaign architect
                  agent (Sonnet) at `campaign init`.

  CampaignState — the per-run save file. Mutates after every mission.
                  Persisted to <campaign_dir>/state.json.

  MissionLink   — one node in the campaign graph: identifies a mission,
                  declares branching successors keyed on outcomes.

  AfterAction   — outcome of one mission, fed in via `campaign report`.

────────────────────────────────────────────────────────────────────
WHEN IMPLEMENTING (Phase 10):

1. Test state persistence FIRST. Write a round-trip test:
   CampaignState → JSON → CampaignState equality.

2. Bump SCHEMA_VERSION whenever a field is added/removed/renamed in
   any model here, and write a migration in campaign/state.py.

3. Do NOT add Pydantic validators that reference *runtime* state
   (e.g. "is this mission name in the missions list?"). Those checks
   belong in campaign/runner.py validation.

4. Keep `extra='allow'` model_config on CampaignState so unknown keys
   from older versions survive round-trip. This is a save-file format,
   not an API.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from .mission import MissionSpec


CAMPAIGN_SCHEMA_VERSION = "0.1.0"


class MissionLink(BaseModel):
    """One node in the campaign graph.

    A mission can be defined inline (spec), loaded from disk (spec_file),
    or generated from a template at run time (spec_template). Exactly one
    of those three must be set.

    Branching: at least one of next_* must be set unless this mission is
    the terminal node.
    """
    name: str = Field(..., description="Unique mission identifier within the campaign")

    # Exactly one of these three sources for the mission body:
    spec: Optional[MissionSpec] = Field(None, description="Inline mission spec")
    spec_file: Optional[str] = Field(None, description="Path to a .json mission spec")
    spec_template: Optional[str] = Field(
        None,
        description="Path to a Jinja2 template; rendered against CampaignState",
    )

    # Branching successors. None = terminal for that outcome.
    next_on_blue_win: Optional[str] = Field(None, description="Next mission name if blue wins")
    next_on_red_win: Optional[str] = Field(None, description="Next mission name if red wins")
    next_on_draw: Optional[str] = Field(None, description="Next mission name on draw")
    next_unconditional: Optional[str] = Field(
        None,
        description="If set, ignores outcome and always goes here next",
    )

    description: Optional[str] = Field(None, description="Author-facing description")


class CampaignState(BaseModel):
    """Per-run persistent state. Mutates after every mission.

    Stored as <campaign_dir>/state.json. The `extra='allow'` config
    means unknown keys from older versions are preserved on round-trip.
    """
    model_config = ConfigDict(extra="allow")

    schema_version: str = Field(default=CAMPAIGN_SCHEMA_VERSION)

    # Where we are in the graph.
    current_mission: Optional[str] = Field(
        None,
        description="Mission name to render next. None when campaign complete.",
    )
    completed_missions: List[str] = Field(
        default_factory=list,
        description="Mission names completed, in order",
    )

    # Score and attrition.
    score: Dict[str, int] = Field(
        default_factory=lambda: {"blue": 0, "red": 0},
        description="Cumulative score per side",
    )
    losses: Dict[str, List[str]] = Field(
        default_factory=lambda: {"blue": [], "red": []},
        description="Unit names lost per side. Names match the spec's group/unit names.",
    )

    # World state.
    captured_airfields: Dict[str, str] = Field(
        default_factory=dict,
        description="airfield_name → side currently holding it",
    )
    flags: Dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary persistent flags. Used by templates to drive variation.",
    )

    # Time progression — campaign day, in-mission date, etc.
    current_date: Optional[datetime] = Field(
        None,
        description="In-fiction date for the next mission",
    )
    day_number: int = Field(1, ge=1, description="Day 1, Day 2, …")


class AfterAction(BaseModel):
    """Outcome of one mission. Submitted via `campaign report`.

    PLAN.md Phase 11 describes three sources for AfterAction:
      A. DCS Lua callback (preferred long-term)
      B. TacView .acmi parsing
      C. Manual CLI (always works, ship first)
    """
    mission_name: str
    winner: Optional[str] = Field(
        None,
        description="'blue', 'red', 'draw', or None for inconclusive",
    )
    blue_score: int = 0
    red_score: int = 0
    blue_losses: List[str] = Field(default_factory=list, description="Lost unit names")
    red_losses: List[str] = Field(default_factory=list)
    captured: Dict[str, str] = Field(
        default_factory=dict,
        description="airfield_name → new owning side",
    )
    flags_set: Dict[str, Any] = Field(
        default_factory=dict,
        description="Mission-set flags to carry into state.flags",
    )
    duration_seconds: Optional[float] = None
    notes: Optional[str] = None


class CampaignSpec(BaseModel):
    """Top-level campaign definition.

    Authored once at `campaign init`. Immutable thereafter — state
    changes go into CampaignState, never here.
    """
    name: str
    theatre: str = Field("Caucasus", description="Theatre — must be in VALID_THEATRES")
    description: Optional[str] = None
    author: Optional[str] = None

    # Graph
    start_mission: str = Field(..., description="Name of the first mission")
    missions: List[MissionLink] = Field(..., min_length=1)

    # Initial state — copied into CampaignState at `campaign init`.
    initial_state: CampaignState = Field(
        default_factory=lambda: CampaignState(current_mission=""),
        description="Seeded into state.json. start_mission is wired in by the runner.",
    )

    # Metadata for the architect agent.
    agent_notes: Optional[str] = Field(
        None, description="Notes from the campaign architect agent"
    )
